## Importing libraries

In [1]:
import numpy as np
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

## numerical data using numpy

In [2]:
marks = np.array([70, 80, 90, 60, 100])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print(marks * 2)
print(marks + 2)

Marks: [ 70  80  90  60 100]
Total: 400
Average: 80.0
Highest: 100
[140 160 180 120 200]
[ 72  82  92  62 102]

## loading dataset

In [3]:
df = pd.read_csv("titanic.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

## head() and tail()

In [4]:
print("First 5 rows:")
display(df.head())

First 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
print("Last 5 rows:")
display(df.tail())

Last 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## shape and columns

In [6]:
print("Dataset shape:", df.shape)
print(df.columns)

Dataset shape: (891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

## info() and describe()

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [8]:
display(df.describe())

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## missing values

In [9]:
display(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## value_counts()

In [10]:
display(df["Survived"].value_counts())
display(df["Pclass"].value_counts())
display(df["Sex"].value_counts())
display(df["Embarked"].value_counts())

Survived
0    549
1    342
Name: count, dtype: int64

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Sex
male      577
female    314
Name: count, dtype: int64

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

## loc and iloc

In [11]:
display(df.loc[:, ["Name", "Sex", "Age"]].head())
female_passengers = df.loc[df["Sex"] == "female", ["Name", "Age", "Survived"]]
display(female_passengers.head(10))
male_passengers = df.loc[df["Sex"] == "male", ["Name", "Age", "Survived"]]
display(male_passengers.head(10))

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

                                                 Name   Age  Survived
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                              Heikkinen, Miss. Laina  26.0         1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
10                    Sandstrom, Miss. Marguerite Rut   4.0         1
11                           Bonnell, Miss. Elizabeth  58.0         1
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0         0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0         1
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0         0

                              Name   Age  Survived
0          Braund, Mr. Owen Harris  22.0         0
4         Allen, Mr. William Henry  35.0         0
5                 Moran, Mr. James   NaN         0
6          McCarthy, Mr. Timothy J  54.0         0
7   Palsson, Master. Gosta Leonard   2.0         0
12  Saundercock, Mr. William Henry  20.0         0
13     Andersson, Mr. Anders Johan  39.0         0
16            Rice, Master. Eugene   2.0         0
17    Williams, Mr. Charles Eugene   NaN         1
20            Fynney, Mr. Joseph J  35.0         0

In [12]:
display(df.iloc[5:19, 0:6])

,PassengerId,Survived,Pclass,Name,Sex,Age
5,6,0,3,"Moran, Mr. James",male,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0
16,17,0,3,"Rice, Master. Eugene",male,2.0
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0

# Custom Questions

## Question 1: How many male passengers over 40 in 2nd class survived?

In [13]:
q1 = df.loc[
    (df["Sex"] == "male") &
    (df["Age"] > 40) &
    (df["Pclass"] == 2) &
    (df["Survived"] == 1)
]

print("Number of survivors matching criteria:", len(q1))
display(q1[["Name", "Age", "Pclass", "Survived"]])

Number of survivors matching criteria: 2

                     Name   Age  Pclass  Survived
288  Hosono, Mr. Masabumi  42.0       2         1
570    Harris, Mr. George  62.0       2         1

In [14]:
q1_total = df.loc[
    (df["Sex"] == "male") &
    (df["Age"] > 40) &
    (df["Pclass"] == 2)
]

print("Total male passengers over 40 in 2nd class:", len(q1_total))
print("Survived:", len(q1))

Total male passengers over 40 in 2nd class: 21
Survived: 2

## Question 2: What was the average fare paid by survivors who embarked from Southampton (S)?

In [15]:
q2 = df.loc[
    (df["Survived"] == 1) &
    (df["Embarked"] == "S"),
    "Fare"
]

print("Number of passengers matching:", len(q2))
print("Average fare:", round(q2.mean(), 2))

Number of passengers matching: 217
Average fare: 39.55

## Findings

**Q1:** Only 2 of the 21 male passengers ove 40 in 2nd class survived, so older men in 2nd class had a low survival rate

**Q2:** Survivors who embarked from Southamptonpaid an average fare of about 39.55, which is higher than the overall median fareof 14.45 from describe().

**Note:** 177 passengers have issing Age, so they are left out of the age filter in Q1.